### ISSUE TITLE
Would be nice to be able to filter on config/state items

### ISSUE THREAD

**Issue by jbemmel** [srl-labs/yang-browser#2]
There is already a "config" / "no config" flag, it would be useful to have a toggle button to show only items in one or the other

**Comment by hellt** [comment]
@siva19susi did we have something like this in nsp telemetry mapper? can't remember

**Comment by siva19susi** [comment]
We did have one on NSP telemetry mapper.

**Comment by hellt** [comment]
@jbemmel 
done, changes are live (docs are not updated yet)
