### ISSUE TITLE
Filtered path is incorrectly displayed

### ISSUE THREAD

**Issue by bclasse** [srl-labs/yang-browser#29]
Some paths are not represented correctly on the YANG browser when using filters. 
For example, `/interface[name=*]/queue-statistics/queue[queue-name=*]/final-dropped-octets` should be displayed for all platforms except D1, and for the ones not containing `future-0-0` feature.

```  {
    "path": "/interface[name=*]/queue-statistics/queue[queue-name=*]/final-dropped-octets",
    "path-with-prefix": "/srl_nokia-if:interface[name=*]/srl_nokia-qos:queue-statistics/queue[queue-name=*]/final-dropped-octets",
    "type": "zero-based-counter64",
    "description": "Number of octets dropped by the queue.\n\nOn 7250-IXR (Jericho2-based) systems unicast packet drops related to egress port congestion should show up in the VOQ stats and not in this statistic.",
    "default": "0",
    "is-state": true,
    "namespace": "urn:srl_nokia/qos",
    "if-features": [
      "not srl-feat:future-0-0",
      "not srl-feat:platform-7220-d1"
    ]
  },
```
Yet this path (and others) appears when filtering on D1 (and don't appear when filtering on D2 for example)

![image](https://user-images.githubusercontent.com/11047599/231651446-0e0b0c01-a232-4f57-837d-384f8f14c4bd.png)

**Comment by hellt** [comment]
Hi @bclasse 
can you please give it a check
@siva19susi (thanks) implemented a fix that is now live

**Comment by bclasse** [comment]
Thanks for the prompt response, that specific field is now correctly filtered, but some others aren't anymore :

![image](https://user-images.githubusercontent.com/11047599/232419656-e2d18aa1-68ee-4384-82b4-95c22f9ee702.png)

**Comment by hellt** [comment]
@bclasse can you ensure that these paths have segment routing if feature set? It might be they don't

**Comment by hellt** [comment]
We synced with Siva and indeed there is an issue (although not related to segment-routing feature). Will keep this open.

**Comment by hellt** [comment]
@bclasse can you give it another look please?
