### ISSUE TITLE
Regenerate paths using gnmic v0.31.0

### ISSUE THREAD

**Issue by bclasse** [srl-labs/yang-browser#35]
Hi,

gnmic v0.31.0 now uses goyang v1.4.0. This fixes an issue in the usage of `if-feature` field in `uses` and `augment` statements. This missed corner case allows some paths to be displayed on the YANG browser for some chassis type, while the path is actually not available.
Could you please regenerate the paths using the new gnmic version to fix the issue? Many thanks

**Comment by bclasse** [comment]
An example of this :

```
  {
    "path": "/interface[name=*]/subinterface[index=*]/qos/input/classifiers/multifield/ipv4-policy",
    (...)    
    "if-features": [
      "not srl-feat:platform-7220-d1"
    ]
  },
  ```
  
  should be 
  ```  
  {
    "path": "/interface[name=*]/subinterface[index=*]/qos/input/classifiers/multifield/ipv4-policy",
    (...)    
    "if-features": [
      "srl_nokia-feat:ip-qos-multifield",
      "not srl-feat:platform-7220-d1"
    ]
  },
```

**Comment by hellt** [comment]
Great work with goyang, @bclasse!
done in #36
