### ISSUE TITLE
"srl_nokia-feat:future-0-0"

### ISSUE THREAD

**Issue by bclasse** [srl-labs/yang-browser#38]
Hi,

Some paths containing `srl_nokia-feat:future-0-0` with another set of if-feature are being displayed on the browser - while they should not, as  `srl_nokia-feat:future-0-0` is not available on any platform. Can you please have a look ?

```  
{
    "path": "/acl/mac-filter[name=*]/entry[sequence-id=*]/action/collect-stats",
    "path-with-prefix": "/srl_nokia-acl:acl/mac-filter[name=*]/entry[sequence-id=*]/action/collect-stats",
    "type": "boolean",
    "description": "Collect statistics for each entry of the ACL. If this is set to false no hardware resources are allocated to collecting statistics for this ACL entry.",
    "default": "false",
    "namespace": "urn:srl_nokia/acl",
    "if-features": [
      "srl_nokia-feat:future-0-0",
      "srl_nokia-feat:platform-7220-d2 or srl_nokia-feat:platform-7220-d3 or srl_nokia-feat:platform-7220-d4 or srl_nokia-feat:platform-7220-d5"
    ]
}
```  
Note, oddly enough, this example is displayed for D3, D3L, D4, D5, D5T, 6(e), 10(e), but not the other platforms.

Also, if possible, could you also add this option in the list of selectable features? 

Many thanks

**Comment by hellt** [comment]
Hi @siva19susi 
can you have a look at that one?

But we won't expose feature-0-0, as this is not expected to be consumed by users.

**Comment by hellt** [comment]
@bclasse can you check now? the fix has been submitted

**Comment by bclasse** [comment]
Looks good to me - thank you both!
