### ISSUE TITLE
Add State/Config filters to YANG Compare

### ISSUE THREAD

**Issue by bclasse** [srl-labs/yang-browser#56]
Hi, it'd be cool to have a filter for state and config paths in the YANG Compare page.
Sometimes users can be interested to just look at the new configurable paths rather than having the whole set of new paths (config+state).

**Comment by bclasse** [comment]
Thanks for adding this, there's just a small display bug. When selecting "RW - Config", it appears as "RW - State". Can you fix this ? Thanks!

![image](https://github.com/user-attachments/assets/79d0591f-ce5f-464b-91c8-1165fd9638a4)

**Comment by siva19susi** [comment]
@bclasse intention was to mention it is filtering Read Write State. But I see your point, what do you think would be a good common name for State and Config to represent the dropdown field?

**Comment by siva19susi** [comment]
@bclasse requested changes are live.
